name: Lab 3 Kubernetes Deployment

on:
  push:
    branches: [lab3]

jobs:
  k8s-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create KinD Cluster
        uses: helm/kind-action@v1.10.0
        with:
          cluster_name: kind

      - name: Deploy to K8s
        run: |
          kubectl apply -f k8s/configmap.yaml
          kubectl apply -f k8s/secret.yaml
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

      - name: Run Master Validation Script
        run: |
          chmod +x ./tests/lab3_test.sh
          ./tests/lab3_test.sh
