name: Lab 4 Helm Validation

on:
  push:
    branches: [lab4]

jobs:
  helm-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: "latest"

      - name: Run Master Validation Script
        run: |
          chmod +x ./tests/lab4_test.sh
          ./tests/lab4_test.sh
